[package]
name = "tests"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
encoding_rs = "0.8.34"
snap = "1.1.1"
xtea = { path = "../block-ciphers/xtea" }
